### ISSUE TITLE
1.20.1 forge jar file doesn't work

### ISSUE THREAD

**Issue by PengyTheGamer** [ErdbeerbaerLP/BluemapFrontiers#3]
quite literally just the file saying it's not a valid mod file

![image](https://github.com/user-attachments/assets/a1c7683c-3ec5-46f7-b93e-b2e768262506)

and thank you for backporting by the way

**Comment by ErdbeerbaerLP** [comment]
[bluemapfrontiers-1.20.1_forge-1.0.0.jar.zip](https://github.com/user-attachments/files/16642400/bluemapfrontiers-1.20.1_forge-1.0.0.jar.zip)
does this one work? 

Also, this is not a clientside mod. it's only for servers

(rename to .jar; github limitation)

**Comment by PengyTheGamer** [comment]
had this problem running on the client
![image](https://github.com/user-attachments/assets/e979ddfc-9eca-41c4-9d71-48d28c4007a8)

seemed to load just fine on a test server though but i got this message (server closed itself a while later, but idk if that had anything to do with this mod)

Exception in thread "Bluemap Frontiers" java.lang.ClassCastException: class games.alejandrocoria.mapfrontiers.common.FrontierData cannot be cast to class de.erdbeerbaerlp.bm_mf.accessors.FrontierDataAccessor (games.alejandrocoria.mapfrontiers.common.FrontierData is in module mapfrontiers@2.6.0p4 of loader 'TRANSFORMER' @4b76aa5a; de.erdbeerbaerlp.bm_mf.accessors.FrontierDataAccessor is in module bluemapfrontiers@1.0.0 of loader 'TRANSFORMER' @4b76aa5a)
        at TRANSFORMER/bluemapfrontiers@1.0.0/de.erdbeerbaerlp.bm_mf.FrontierTask.lambda$run$2(FrontierTask.java:40)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at TRANSFORMER/bluemapfrontiers@1.0.0/de.erdbeerbaerlp.bm_mf.FrontierTask.lambda$run$3(FrontierTask.java:39)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at TRANSFORMER/bluemapfrontiers@1.0.0/de.erdbeerbaerlp.bm_mf.FrontierTask.run(FrontierTask.java:27)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
        
        
also i am aware it's not a client side mod, was just using it to test

**Comment by ErdbeerbaerLP** [comment]
This one will work tho

found the issue. another thing where forge is diff from neoforge

https://modrinth.com/mod/bluemapfrontiers/version/e6SxXn7W
